### ISSUE TITLE
Manual Installation of AndroidTamer

### ISSUE THREAD

**Issue by 0xbadshah** [AndroidTamer/Tools_Repository#100]
## Manual Installation of AndroidTamer on Debian 8 Minimal OS

Configured the repositories and added gpg key of Tamer

![screenshot 128](https://cloud.githubusercontent.com/assets/12944530/16575408/995e2a0e-42a5-11e6-8a48-3d64a4ea4a33.png)

I get all the tools which is installed in Tamer 4 ova file, but I get an error when I **mark everything for installation** as stated below:

![screenshot 127](https://cloud.githubusercontent.com/assets/12944530/16575536/b4a1308a-42a6-11e6-8368-0e06cfdf49e3.png)

**Detailed error:**

```
androidtamer-dev:
 Depends: proguard but it is not going to be installed
 Depends: fastjar but it is not going to be installed
 Depends: jaligner  but it is not installable
 Depends: jarwrapper but it is not going to be installed
 Depends: visualvm but it is not going to be installed
 Depends: gradle but it is not going to be installed

androidtamer-essential:
 Depends: mate-desktop-environment but it is not going to be installed
 Depends: mate-system-tools but it is not going to be installed
 Depends: mate-netspeed but it is not going to be installed
 Depends: lightdm but it is not going to be installed
 Depends: caja-gksu but it is not going to be installed
 Depends: caja-extensions-common but it is not going to be installed
 Depends: caja-sendto but it is not going to be installed
 Depends: caja-open-terminal but it is not going to be installed
 Depends: openjdk-7-jdk but it is not going to be installed
 Depends: default-jdk but it is not going to be installed
 Depends: openjdk-8-jdk  but it is not installable
 Depends: libc6-i386 but it is not going to be installed
 Depends: lib32stdc++6 but it is not going to be installed
 Depends: lib32gcc1 but it is not going to be installed
 Depends: lib32ncurses5 but it is not going to be installed
 Depends: lib32z1 but it is not going to be installed
 Depends: vim
 Depends: terminator but it is not going to be installed
 Depends: git but it is not going to be installed
 Depends: subversion but it is not going to be installed
 Depends: exfat-fuse but it is not going to be installed
 Depends: exfat-utils but it is not going to be installed
 Depends: mtp-tools but it is not going to be installed
 Depends: curl but it is not going to be installed
 Depends: sqlcipher  but it is not installable
 Depends: sqlite but it is not going to be installed
 Depends: sqlitebrowser but it is not going to be installed
 Depends: python-frida but it is not going to be installed
 Depends: geany but it is not going to be installed
 Depends: geany-plugin-treebrowser but it is not going to be installed
 Depends: ratproxy but it is not going to be installed
 Depends: proxychains but it is not going to be installed
 Depends: tsocks but it is not going to be installed
 Depends: redsocks but it is not going to be installed
 Depends: websockify but it is not going to be installed
 Depends: wifite but it is not going to be installed
 Depends: chaosreader but it is not going to be installed
 Depends: dsniff but it is not going to be installed
 Depends: chromium but it is not going to be installed
 Depends: openvpn but it is not going to be installed

androidtamer-forensics:
 Depends: volatility but it is not going to be installed
 Depends: lime-forensics-dkms but it is not going to be installed
 Depends: autopsy but it is not going to be installed
 Depends: dc3dd but it is not going to be installed
 Depends: dcfldd but it is not going to be installed
 Depends: dff but it is not going to be installed
 Depends: ext4magic but it is not going to be installed
 Depends: scalpel but it is not going to be installed
 Depends: sleuthkit but it is not going to be installed
 Depends: vinetto but it is not going to be installed
 Depends: volatility-tools but it is not going to be installed
 Depends: exif but it is not going to be installed
 Depends: libimage-exif-perl but it is not going to be installed
 Depends: exiv2 but it is not going to be installed
 Depends: python-exif but it is not going to be installed
 Depends: metacam but it is not going to be installed
 Depends: exiftags but it is not going to be installed
 Depends: jhead but it is not going to be installed
 Depends: exifprobe but it is not going to be installed
 Depends: testdisk but it is not going to be installed
 Depends: steghide but it is not going to be installed
 Depends: iwatch but it is not going to be installed
 Depends: forensics-all  but it is not installable
 Depends: guymager but it is not going to be installed
 Depends: rdd but it is not going to be installed
 Depends: xmount but it is not going to be installed
 Depends: fatcat but it is not going to be installed
 Depends: foremost but it is not going to be installed

androidtamer-manualanalysis:
 Depends: sqlcipher  but it is not installable
 Depends: sqlite but it is not going to be installed
 Depends: sqlitebrowser but it is not going to be installed
 Depends: python-frida but it is not going to be installed

androidtamer-pentesting:
 Depends: nikto  but it is not installable
 Depends: w3af but it is not going to be installed
 Depends: w3af-console but it is not going to be installed
 Depends: wapiti but it is not going to be installed
 Depends: ratproxy but it is not going to be installed
 Depends: skipfish but it is not going to be installed
 Depends: spikeproxy but it is not going to be installed
 Depends: hydra but it is not going to be installed
 Depends: hydra-gtk but it is not going to be installed
 Depends: jxplorer but it is not going to be installed
 Depends: wireshark but it is not going to be installed
 Depends: hping3 but it is not going to be installed
 Depends: mz but it is not going to be installed
 Depends: mitmproxy but it is not going to be installed
 Depends: sslstrip but it is not going to be installed
 Depends: ettercap-graphical but it is not going to be installed
 Depends: ettercap-common but it is not going to be installed
 Depends: sslscan but it is not going to be installed
 Depends: stunnel
 Depends: socat but it is not going to be installed
 Depends: zaproxy but it is not going to be installed
 Depends: tcpdump but it is not going to be installed
 Depends: tshark but it is not going to be installed
 Depends: proxychains but it is not going to be installed
 Depends: tsocks but it is not going to be installed
 Depends: redsocks but it is not going to be installed
 Depends: websockify but it is not going to be installed

yadd-dumper:
 Depends: libc  but it is not installable
```
